name: flutter_doanlt
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  http: ^1.2.2
  json_serializable: ^6.1.0
  build_runner: ^2.3.3
  flutter_lints: ^3.0.0
  dio: ^5.5.0+1
  sqflite: ^2.2.6
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.14
  path: ^1.8.2
  image_picker: ^1.1.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.3.0
  go_router: ^14.2.1
  auto_route: ^8.3.0
  provider: ^6.1.2
  mime: ^1.0.5
  http_parser: ^4.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/zalo_pay.jpg
    - assets/images/paypal_logo.jpg
    - assets/images/cod_logo.jpg
    - assets/images/
    - assets/file/shoe_data.json
